#pragma config(Sensor, in1,    mogoPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveEncoderR,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveEncoderL,  sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  intake,         sensorDigitalOut)
#pragma config(Sensor, dgtl6,  fourBar,        sensorDigitalOut)
#pragma config(Sensor, dgtl7,  intakeSensor,   sensorDigitalIn)
#pragma config(Motor,  port1,           driveRB,       tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRM,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRF,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           liftLB,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftLT,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           liftRB,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           liftRT,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveLF,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           driveLM,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveLB,       tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "utilities.c"
//#include "tinyExpr/tinyExpr.h"
#include "subsystemFunctions.c"
#include "PID.c"
#include "PIDCreation.h"
#include "mogoDriveControl.c"
#include "liftControl.c"
#include "stackingVariables.h"
#include "stackingMasterControl.c"
#include "autons.c"

string autons[] = {"hi", "hello", "my boy"};//list of 14 character strings naming autons
#include "autonSelect.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
	stopTask(autonSelect);
	startTask(autonSelect);
	//resetGyro();
}

task autonomous()
{
   switch(autonType){
		case 0:
		displayAuton(autonType);
			fourConesIn20();
		break;
		case 1:
		displayAuton(autonType);

		break;
		case 2:
		displayAuton(autonType);

		break;
		default:
		break;
	}
}


task usercontrol(){
	startTask(mogoDriveControl);
}
