#pragma config(Sensor, in1,    mogoPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  driveEncoderR,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveEncoderL,  sensorQuadEncoder)
#pragma config(Motor,  port1,           driveRB,       tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRM,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveRF,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveLF,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           driveLM,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          driveLB,       tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "utilities.c"
#include "PID.c"
#include "PIDCreation.h"
#include "mogoDriveControl.c"

string autons[] = {"hi", "hello", "my boy"};//list of 14 character strings naming autons
#include "autonSelect.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
	stopTask(autonSelect);
	startTask(autonSelect);
	//resetGyro();
}

task autonomous()
{
   switch(autonType){
		case 0:
		displayAuton(autonType);

		break;
		case 1:
		displayAuton(autonType);

		break;
		case 2:
		displayAuton(autonType);

		break;
		default:
		break;
	}
}


task usercontrol()
{
	startTask(mogoDriveControl);
	/*clearDebugStream();
	int mogoMotorValue, motorValueL, motorValueR;
	struct PIDLoop mogoPID;
	initializePIDLoop(mogoPID, 0.1, 0.00002, 5, 100, 1000, mogoPot);
	struct PIDLoop leftDrivePID;
	initializePIDLoop(leftDrivePID, 1, 0.0005, 15, 1, 1000, driveEncoderL);
	struct PIDLoop rightDrivePID;
	initializePIDLoop(rightDrivePID, 1, 0.0005, 15, 1, 1000, driveEncoderR);
	while(true){
		mogoPID.desiredValue = desiredMogo;
		motorValueL = limit(calculatePIDValue(leftDrivePID));
		motor[driveLF] = motor[driveLB] = motorValueL;

		motorValueR = limit(calculatePIDValue(rightDrivePID));
		motor[driveRF] = motor[driveRB] = motorValueR;

		mogoMotorValue = limit(calculatePIDValue(mogoPID));
		motor[driveLM] = motor[driveRM] = -mogoMotorValue;

		wait1Msec(50);
	}*/
}
